-- MySQL Script generated by Johannes Tomren Røsvik,
-- Dennis Jianbin Liang, Pål Fossnes, Fredrik Jenssen
-- Tue Mar  6 15:23:22 2018

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema WorkoutDiary
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `WorkoutDiary` ;
CREATE SCHEMA IF NOT EXISTS `WorkoutDiary` DEFAULT CHARACTER SET utf8 ;
USE `WorkoutDiary` ;

-- -----------------------------------------------------
-- Table `WorkoutDiary`.`Workout`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WorkoutDiary`.`Workout` ;

CREATE TABLE IF NOT EXISTS `WorkoutDiary`.`Workout` (
  `Date` DATE NOT NULL,
  `startTime` TIME NOT NULL,
  `shape` INT NOT NULL,
  `note` VARCHAR(255) NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `WorkoutDiary`.`Exercise`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WorkoutDiary`.`Exercise` ;

CREATE TABLE IF NOT EXISTS `WorkoutDiary`.`Exercise` (
  `name` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `WorkoutDiary`.`Equipment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WorkoutDiary`.`Equipment` ;

CREATE TABLE IF NOT EXISTS `WorkoutDiary`.`Equipment` (
  `description` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `WorkoutDiary`.`ExerciseGroup`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WorkoutDiary`.`ExerciseGroup` ;

CREATE TABLE IF NOT EXISTS `WorkoutDiary`.`ExerciseGroup` (
  `name` VARCHAR(255) NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `WorkoutDiary`.`Exercise_has_ExerciseGroup`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WorkoutDiary`.`Exercise_has_ExerciseGroup` ;

CREATE TABLE IF NOT EXISTS `WorkoutDiary`.`Exercise_has_ExerciseGroup` (
  `Exercise_id` INT NOT NULL,
  `ExerciseGroup_id` INT NOT NULL,
  PRIMARY KEY (`Exercise_id`, `ExerciseGroup_id`),
  INDEX `fk_Exercise_has_ExerciseGroup_ExerciseGroup1_idx` (`ExerciseGroup_id` ASC),
  INDEX `fk_Exercise_has_ExerciseGroup_Exercise1_idx` (`Exercise_id` ASC),
  CONSTRAINT `fk_Exercise_has_ExerciseGroup_Exercise1`
  FOREIGN KEY (`Exercise_id`)
  REFERENCES `WorkoutDiary`.`Exercise` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Exercise_has_ExerciseGroup_ExerciseGroup1`
  FOREIGN KEY (`ExerciseGroup_id`)
  REFERENCES `WorkoutDiary`.`ExerciseGroup` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `WorkoutDiary`.`Workout_has_Exercise`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WorkoutDiary`.`Workout_has_Exercise` ;

CREATE TABLE IF NOT EXISTS `WorkoutDiary`.`Workout_has_Exercise` (
  `Workout_id` INT NOT NULL,
  `Exercise_id` INT NOT NULL,
  `duration` TIME NOT NULL,
  `performance` INT NOT NULL,
  PRIMARY KEY (`Workout_id`, `Exercise_id`),
  INDEX `fk_Workout_has_Exercise_Exercise1_idx` (`Exercise_id` ASC),
  INDEX `fk_Workout_has_Exercise_Workout1_idx` (`Workout_id` ASC),
  CONSTRAINT `fk_Workout_has_Exercise_Workout1`
  FOREIGN KEY (`Workout_id`)
  REFERENCES `WorkoutDiary`.`Workout` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Workout_has_Exercise_Exercise1`
  FOREIGN KEY (`Exercise_id`)
  REFERENCES `WorkoutDiary`.`Exercise` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `WorkoutDiary`.`Exercise_has_Equipment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WorkoutDiary`.`Exercise_has_Equipment` ;

CREATE TABLE IF NOT EXISTS `WorkoutDiary`.`Exercise_has_Equipment` (
  `Exercise_id` INT NOT NULL,
  `Equipment_id` INT NOT NULL,
  `kilos` FLOAT NULL,
  `sets` INT NULL,
  PRIMARY KEY (`Exercise_id`, `Equipment_id`),
  INDEX `fk_Exercise_has_Equipment_Equipment1_idx` (`Equipment_id` ASC),
  INDEX `fk_Exercise_has_Equipment_Exercise1_idx` (`Exercise_id` ASC),
  CONSTRAINT `fk_Exercise_has_Equipment_Exercise1`
  FOREIGN KEY (`Exercise_id`)
  REFERENCES `WorkoutDiary`.`Exercise` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Exercise_has_Equipment_Equipment1`
  FOREIGN KEY (`Equipment_id`)
  REFERENCES `WorkoutDiary`.`Equipment` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
